spring:
  datasource:
    password: osf77
    url: jdbc:postgresql://localhost/gastos?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: soza
  jpa:
    database: POSTGRESQL
  flyway:
    locations: classpath:db/migration